ClienteMVC/ClienteMVC/Controllers/TipoEnderecoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClienteMVC.Entity;
using ClienteMVC.Models;
using ClienteMVC.ViewModels;

namespace ClienteMVC.Controllers
{
    public class TipoEnderecoController : Controller
    {

        private TipoEnderecoModel teModel = new TipoEnderecoModel();

        public ActionResult Index()
        {
            TipoEnderecoViewModel vm = new TipoEnderecoViewModel();
            vm.tiposEndereco = teModel.todosTipoEnderecos();
            return View(vm);
        }

        public PartialViewResult List(string q)
        {
            var tiposEndereco = teModel.listarTipoEnderecos(q);
            return PartialView(tiposEndereco);
        }

    }
}

ClienteMVC/ClienteMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Styles.Render("~/Content/themes/base/css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/jqueryui")
        @Scripts.Render("~/bundles/priceformat")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>

                            @if (System.Web.Security.Roles.IsUserInRole(User.Identity.Name,
                                "Administrador"))
                            {
                                <li>@Html.ActionLink("Cliente", "Index", "Cliente")</li>
                            }
                            <li>@Html.ActionLink("Tipo Endereço", "Index", "TipoEndereco")</li>
                            <li>@Html.ActionLink("Marca", "Index", "Marca")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        
        @RenderSection("scripts", required: false)
    </body>
</html>